name: Convert

on: push
env:
   ARTIFACT_PATH: yaml
   ARTIFACT_NAME: my-yaml
   ARTIFACT_FILENAME: example.yml

jobs:
 converter:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Convert json to yaml
     uses: fabasoad/yaml-json-xml-converter-action@main
     id: json2yaml
     with:
       path: 'json/example.json'
       from: 'json'
       to: 'yaml'

   - name: Create desired directories
     run: mkdir -p "${{ env.ARTIFACT_PATH }}"
   - name: Route converter output into specified file
     run: echo "${{ steps.json2yaml.outputs.data }}" > ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_FILENAME }}

   - name: Upload exported directory to the repository
     uses: actions/upload-artifact@v2
     with:
      name: ${{ env.ARTIFACT_NAME }}
      path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_FILENAME }}
